version: 2
jobs:
  test:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    steps:
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${streetchange-988ad}
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run
              --app C:\Users\PKEAV\Desktop\Senior\FYP\StreetShare\platforms\android\app\build\outputs\apk\debug\app-debug.apk
              --test C:\Users\PKEAV\Desktop\Senior\FYP\StreetShare\platforms\android\app\build\outputs\apk\debug\app-debug.apk
              --results-bucket cloud-test-${streetchange-988ad}
      