version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-26-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ .Branch }}-{{ checksum  "package-lock.json" }}
      
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ .Branch }}-{{ checksum  "package-lock.json" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      
      - run:
          name: Dump Google Cloud Credentials to file
          command: echo ${GOOGLE_AUTH} > /home/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file /home/gcloud-service-key.json
      - run: gcloud --quiet config set project streetchange-988ad
      - run:
          name: Configure environment
          command: |
            echo 'export APK_PATH=`find . -path "*.apk" ! -path "*unaligned.apk" ! -path "*Test*.apk" -print -quit`' >> $BASH_ENV
            echo 'export TEST_APK_PATH=`find "." "-path" "*Test*.apk" -print -quit`' >> $BASH_ENV
      - run:
          name: Run UI Tests
          command: gcloud firebase test android run --type instrumentation --app \platforms\android\app\build\outputs\apk\debug\app-debug.apk --test \platforms\android\app\build\outputs\apk\debug\app-debug-androidTest.apk --device model=Nexus6P,version=27,locale=en,orientation=portrait --timeout 30m
          no_output_timeout: 30m